source 'https://github.com/CocoaPods/Specs.git'

target 'HelloSwift' do
    platform :ios, '8.0'
    use_frameworks!
    
    pod 'Appboy-iOS-SDK'
end

target 'HelloSwiftTVOS' do
    platform :tvos, '10.0'
    use_frameworks!
    
    pod 'Appboy-tvOS-SDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        if target.name == "Appboy-iOS-SDK"
            config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
        end
        if target.name == "Appboy-tvOS-SDK"
            config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
        end
    end
  end
end
